# Form implementation generated from reading ui file 'src/assets/uiFiles/hotkeyForm.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HotkeyWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 100)
        self.hotkeyLabel = QtWidgets.QLabel(parent=Form)
        self.hotkeyLabel.setGeometry(QtCore.QRect(156, 10, 131, 79))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hotkeyLabel.setFont(font)
        self.hotkeyLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hotkeyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hotkeyLabel.setObjectName("hotkeyLabel")
        self.setHotkeyButton = QtWidgets.QPushButton(parent=Form)
        self.setHotkeyButton.setGeometry(QtCore.QRect(10, 10, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.setHotkeyButton.setFont(font)
        self.setHotkeyButton.setObjectName("setHotkeyButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hotkey"))
        self.hotkeyLabel.setText(_translate("Form", "F6"))
        self.setHotkeyButton.setText(_translate("Form", "Set Hotkey\n"
"(Start/Stop)"))
