# Form implementation generated from reading ui file 'src/assets/uiFiles/autoclickerUI.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 383)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #1a1a2e;\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3a86ff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f3460;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2c303d\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #e0e0e0;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    border: 1px solid #0f3460;\n"
"    border-radius: 7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #3a86ff;\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: #16213e;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #16213e;\n"
"    color: #e0e0e0;\n"
"    selection-background-color: #3a86ff;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #3a86ff;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"}\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: #3a86ff;\n"
"}")
        self.startButton = QtWidgets.QPushButton(parent=Form)
        self.startButton.setGeometry(QtCore.QRect(10, 240, 141, 61))
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(parent=Form)
        self.stopButton.setGeometry(QtCore.QRect(240, 310, 151, 61))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.intervalEditLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.intervalEditLayout.setContentsMargins(40, 0, 40, 0)
        self.intervalEditLayout.setSpacing(40)
        self.intervalEditLayout.setObjectName("intervalEditLayout")
        self.intervalEdit2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.intervalEdit2.setText("")
        self.intervalEdit2.setObjectName("intervalEdit2")
        self.intervalEditLayout.addWidget(self.intervalEdit2)
        self.intervalEdit1 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.intervalEdit1.setText("")
        self.intervalEdit1.setObjectName("intervalEdit1")
        self.intervalEditLayout.addWidget(self.intervalEdit1)
        self.hotkeyButton = QtWidgets.QPushButton(parent=Form)
        self.hotkeyButton.setGeometry(QtCore.QRect(10, 310, 141, 61))
        self.hotkeyButton.setCheckable(False)
        self.hotkeyButton.setObjectName("hotkeyButton")
        self.secondsLabel = QtWidgets.QLabel(parent=Form)
        self.secondsLabel.setGeometry(QtCore.QRect(40, 41, 141, 16))
        self.secondsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.secondsLabel.setObjectName("secondsLabel")
        self.millisecondsLabel = QtWidgets.QLabel(parent=Form)
        self.millisecondsLabel.setGeometry(QtCore.QRect(220, 40, 141, 20))
        self.millisecondsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.millisecondsLabel.setObjectName("millisecondsLabel")
        self.setIntervalLabel = QtWidgets.QLabel(parent=Form)
        self.setIntervalLabel.setGeometry(QtCore.QRect(10, 10, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setIntervalLabel.setFont(font)
        self.setIntervalLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.setIntervalLabel.setObjectName("setIntervalLabel")
        self.clickModeFrame = QtWidgets.QFrame(parent=Form)
        self.clickModeFrame.setGeometry(QtCore.QRect(10, 100, 201, 131))
        self.clickModeFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.clickModeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.clickModeFrame.setObjectName("clickModeFrame")
        self.clickTypeLabel = QtWidgets.QLabel(parent=self.clickModeFrame)
        self.clickTypeLabel.setGeometry(QtCore.QRect(60, 50, 51, 31))
        self.clickTypeLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.clickTypeLabel.setObjectName("clickTypeLabel")
        self.keyboardModeToggle = QtWidgets.QRadioButton(parent=self.clickModeFrame)
        self.keyboardModeToggle.setGeometry(QtCore.QRect(10, 90, 82, 31))
        self.keyboardModeToggle.setObjectName("keyboardModeToggle")
        self.setKeyButton = QtWidgets.QPushButton(parent=self.clickModeFrame)
        self.setKeyButton.setGeometry(QtCore.QRect(90, 90, 51, 31))
        self.setKeyButton.setObjectName("setKeyButton")
        self.clickTypeComboBox = QtWidgets.QComboBox(parent=self.clickModeFrame)
        self.clickTypeComboBox.setGeometry(QtCore.QRect(120, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clickTypeComboBox.setFont(font)
        self.clickTypeComboBox.setObjectName("clickTypeComboBox")
        self.clickTypeComboBox.addItem("")
        self.clickTypeComboBox.addItem("")
        self.clickTypeComboBox.addItem("")
        self.keyLabel = QtWidgets.QLabel(parent=self.clickModeFrame)
        self.keyLabel.setGeometry(QtCore.QRect(150, 90, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.keyLabel.setFont(font)
        self.keyLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.keyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.keyLabel.setObjectName("keyLabel")
        self.mouseButtonLabel = QtWidgets.QLabel(parent=self.clickModeFrame)
        self.mouseButtonLabel.setGeometry(QtCore.QRect(90, 10, 41, 31))
        self.mouseButtonLabel.setObjectName("mouseButtonLabel")
        self.mouseButtonsBox = QtWidgets.QComboBox(parent=self.clickModeFrame)
        self.mouseButtonsBox.setGeometry(QtCore.QRect(130, 10, 71, 31))
        self.mouseButtonsBox.setObjectName("mouseButtonsBox")
        self.mouseButtonsBox.addItem("")
        self.mouseButtonsBox.addItem("")
        self.mouseButtonsBox.addItem("")
        self.mouseModeToggle = QtWidgets.QRadioButton(parent=self.clickModeFrame)
        self.mouseModeToggle.setGeometry(QtCore.QRect(10, 10, 61, 31))
        self.mouseModeToggle.setObjectName("mouseModeToggle")
        self.repeatModeFrame = QtWidgets.QFrame(parent=Form)
        self.repeatModeFrame.setGeometry(QtCore.QRect(220, 100, 171, 131))
        self.repeatModeFrame.setStyleSheet("/* Основной стиль для всего приложения */\n"
"QWidget {\n"
"    background-color: #1a1a2e;\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"/* Стиль для кнопок QPushButton с градиентом */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #16213e, stop:1 #4da6ff);\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #3a86ff, stop:1 #4da6ff);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #0f3460, stop:1 #3a86ff);\n"
"}\n"
"/* СТИЛЬ ДЛЯ ОТКЛЮЧЕННЫХ КНОПОК */\n"
"QPushButton:disabled {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #2a2a3e, stop:1 #3d4b5d);\n"
"    border: 1px solid #1c1c3a;\n"
"    color: #7a7a8c;\n"
"}\n"
"\n"
"/* Стиль для радиокнопок QRadioButton */\n"
"QRadioButton {\n"
"    color: #e0e0e0;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    border: 1px solid #0f3460;\n"
"    border-radius: 7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #4da6ff;\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: #16213e;\n"
"}\n"
"\n"
"/* Стиль для выпадающих списков QComboBox */\n"
"QComboBox {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    /* Можно указать путь к иконке: image: url(path/to/down_arrow.png); */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #16213e;\n"
"    color: #e0e0e0;\n"
"    selection-background-color: #4da6ff;\n"
"}\n"
"\n"
"/* Стиль для полей ввода QLineEdit */\n"
"QLineEdit {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #4da6ff;\n"
"}\n"
"\n"
"/* Стиль для числовых полей QSpinBox */\n"
"QSpinBox {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"    color: #e0e0e0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: #16213e;\n"
"    border: 1px solid #0f3460;\n"
"}\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: #4da6ff;\n"
"}")
        self.repeatModeFrame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.repeatModeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.repeatModeFrame.setObjectName("repeatModeFrame")
        self.repeatTimesLabel = QtWidgets.QLabel(parent=self.repeatModeFrame)
        self.repeatTimesLabel.setGeometry(QtCore.QRect(130, 70, 47, 31))
        self.repeatTimesLabel.setObjectName("repeatTimesLabel")
        self.repeatUntilStoppedToggle = QtWidgets.QRadioButton(parent=self.repeatModeFrame)
        self.repeatUntilStoppedToggle.setGeometry(QtCore.QRect(10, 26, 131, 31))
        self.repeatUntilStoppedToggle.setObjectName("repeatUntilStoppedToggle")
        self.repeatTimesToggle = QtWidgets.QRadioButton(parent=self.repeatModeFrame)
        self.repeatTimesToggle.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.repeatTimesToggle.setObjectName("repeatTimesToggle")
        self.repeatSpinBox = QtWidgets.QSpinBox(parent=self.repeatModeFrame)
        self.repeatSpinBox.setGeometry(QtCore.QRect(80, 70, 42, 31))
        self.repeatSpinBox.setObjectName("repeatSpinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AutoClicker"))
        self.startButton.setText(_translate("Form", "Start"))
        self.stopButton.setText(_translate("Form", "Stop"))
        self.intervalEdit2.setPlaceholderText(_translate("Form", "interval in seconds"))
        self.intervalEdit1.setPlaceholderText(_translate("Form", "interval in milliseconds"))
        self.hotkeyButton.setText(_translate("Form", "Hotkey"))
        self.secondsLabel.setText(_translate("Form", "Seconds"))
        self.millisecondsLabel.setText(_translate("Form", "Milliseconds"))
        self.setIntervalLabel.setText(_translate("Form", "Set interval"))
        self.clickTypeLabel.setText(_translate("Form", "Click type"))
        self.keyboardModeToggle.setText(_translate("Form", "Keyboard"))
        self.setKeyButton.setText(_translate("Form", "Set key"))
        self.clickTypeComboBox.setItemText(0, _translate("Form", "Single"))
        self.clickTypeComboBox.setItemText(1, _translate("Form", "Double"))
        self.clickTypeComboBox.setItemText(2, _translate("Form", "Triple"))
        self.keyLabel.setText(_translate("Form", "A"))
        self.mouseButtonLabel.setText(_translate("Form", "Button"))
        self.mouseButtonsBox.setItemText(0, _translate("Form", "Left"))
        self.mouseButtonsBox.setItemText(1, _translate("Form", "Right"))
        self.mouseButtonsBox.setItemText(2, _translate("Form", "Middle"))
        self.mouseModeToggle.setText(_translate("Form", "Mouse"))
        self.repeatTimesLabel.setText(_translate("Form", "times"))
        self.repeatUntilStoppedToggle.setText(_translate("Form", "Repeat until stopped"))
        self.repeatTimesToggle.setText(_translate("Form", "Repeat"))
